### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by sahandnayebaziz** [jamesssooi/Croppr.js#4]
It would be great if this worked on iOS, Android, and other touch devices!

**Comment by jamesssooi** [comment]
That's definitely coming and in-progress!

**Comment by jamesssooi** [comment]
Touch devices are now supported (tested on iPhone and iPad) with the latest release (391ddd1).

**Comment by sahandnayebaziz** [comment]
Awesome @jamesssooi :)
