### ISSUE TITLE
Typescript Translate

### ISSUE THREAD

**Issue by aljibbs** [jamesssooi/Croppr.js#6]
Will you translate this library into a typescript version anytime soon ?

**Comment by jamesssooi** [comment]
Hi @aljibbs, while I do see the merits of Typescript (and loving it!), I don't see a big reason to port the whole project over to Typescript given its relatively small code base.

Or do you mean creating type definition files for Croppr?

**Comment by aljibbs** [comment]
Yeah that's what I meant. Will you create  type definitions for Croppr ?

**Comment by jamesssooi** [comment]
It's definitely a great helpful addition. I'm already working on it, so do expect it to be released the next few days!

**Comment by jamesssooi** [comment]
Typescript typings has been added and released in [v2.2.1](https://github.com/jamesssooi/Croppr.js/releases/tag/v2.2.1). Happy coding in confidence and safety!
