### ISSUE TITLE
Event "cropEnd"

### ISSUE THREAD

**Issue by kaermorchen** [jamesssooi/Croppr.js#7]
Hi. 

@jamesssooi  your Croppr.js is really cool, but using `onUpdate` event is too frequent for calculate new image.

Can I use "cropEnd" event (or something like that) when user has stoped crop?

**Comment by jamesssooi** [comment]
That's a really good suggestion @kaermorchen, will definitely work that in an update the next few days. Thanks!

**Comment by jamesssooi** [comment]
I've added the following three new callbacks in the develop branch. You can read the latest documentation [here](https://github.com/jamesssooi/Croppr.js/tree/develop#oncropstart).

  * **`onCropStart`:** Triggers when users start modifying the crop region
  * **`onCropMove`**: Triggers when crop region changes (similar to the current `onUpdate`)
  * **`onCropEnd`**: Triggers when users stop modifying the crop region

I realised `onUpdate` can be confusing as it could mean either `onCropMove` or `onCropEnd`. As such, I've decided to also deprecate the existing `onUpdate` callback to create a more uniform, consistent, and less ambiguous API.

It will still remain in Croppr.js however for backwards compatibility purposes, but will be removed after one or two major releases. Developers still using `onUpdate` will see deprecation notices in their console.

Let me know what you think before I merge it into master and package a new release on npm!

**Comment by kaermorchen** [comment]
Yes, that is what I needed. So fast update. Thank you.

**Comment by jamesssooi** [comment]
Issued a new release with the new callbacks as [`v2.0.0`](https://github.com/jamesssooi/Croppr.js/tree/v2.0.0) in npm. Closing this for now.
