### ISSUE TITLE
Destroy instance?

### ISSUE THREAD

**Issue by danielsarin** [jamesssooi/Croppr.js#8]
I couldn't find a method for destroying the cropper instance and restoring the image element as it was. Can this be done or could this be implemented?

**Comment by jamesssooi** [comment]
You're right, a destroy method should be available. Will put this in the next release, thanks!

**Comment by jamesssooi** [comment]
I've added the `destroy` method in the latest release (v2.1.0). Calling the instance's destroy method will now remove all of Croppr's DOM elements and replace it with the original `img` element. 

Internally Croppr stores a reference to the original DOM element, so once the instance is destroyed, it is replaced with the exact same copy of the original DOM element. Meaning all event listenrs are retained 🎉 .

Closing this for now.
