### ISSUE TITLE
Canvas support

### ISSUE THREAD

**Issue by mbwhite** [jamesssooi/Croppr.js#9]
I've been reviewing the code to check if it's possible to apply Croppr.is to  a canvas. 
Would this be possible?

I understand that the aim of Croppr is get the size selection and then crop later.

**Comment by jamesssooi** [comment]
Hi @mbwhite, do you mean drawing the Croppr UI on top of a canvas? Or do you mean using Croppr to crop an existing canvas context? If it's the latter, you can refer to [this comment](https://github.com/jamesssooi/Croppr.js/issues/3#issuecomment-296896272) I've made in another thread.

**Comment by mbwhite** [comment]
@jamesssooi ... I've an existing canvas element and the wish is to display the Croppr UI on top that. 
So the user can specify how they believe the canvas should be cropped.  It will contain an image - but also other elements drawn hence using a canvas.

**Comment by jamesssooi** [comment]
If you inspect Croppr's DOM, you'd see that Croppr's elements (handles, boxes, etc) are simply laid on top of an <img> element.

So in theory, with some modifications to Croppr you can make it overlay these elements on top of your `<canvas>` element instead. Have a look inside the [`createDOM()`](https://github.com/jamesssooi/Croppr.js/blob/master/src/core.js#L106) method where it creates the `<img>` element.

An alternative method is to simply create an `<img>` element with it's src from your canvas using the [`fromDataUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) method. Then let Croppr work on that img element natively.

**Comment by mbwhite** [comment]
@jamesssooi Thanks for the update - sorry I didn't respond earlier.   
I've found the section of code you mention; will see what I can do.  

Will close this issue.

**Comment by signalpoint** [comment]
[This comment](https://github.com/jamesssooi/Croppr.js/issues/31#issuecomment-854963544) appears to have a solid example of drawing the Croppr selection onto a canvas element.
